import { useEffect, useState } from 'react';
import Layout from '../Layout';
import api from '../../services/api';

interface Pattern {
  id: number;
  disease_type: string;
  pattern_description: string | null;
  confidence_score: number | null;
  data_points_used: number | null;
  active: boolean;
  last_updated: string;
}

function ConfidenceBar({ score }: { score: number | null }) {
  if (score == null) return <span style={{ color: 'var(--text-muted)' }}>—</span>;
  const pct = Math.round(score * 100);
  const color = pct >= 75 ? 'var(--emerald)' : pct >= 50 ? 'var(--amber)' : 'var(--rose)';
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
      <div style={{ flex: 1, height: 6, background: 'rgba(255,255,255,0.1)', borderRadius: 3 }}>
        <div style={{ width: `${pct}%`, height: '100%', background: color, borderRadius: 3, transition: 'width 0.6s ease' }} />
      </div>
      <span style={{ fontSize: '0.78rem', color, minWidth: 36 }}>{pct}%</span>
    </div>
  );
}

export default function PatternList() {
  const [patterns, setPatterns] = useState<Pattern[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    api.get<Pattern[]>('/patterns?limit=200')
      .then(({ data }) => setPatterns(data))
      .catch((err) => {
        if ((err as { response?: { status?: number } })?.response?.status === 404) {
          setPatterns([]);
        } else {
          setError('Failed to load patterns.');
        }
      })
      .finally(() => setLoading(false));
  }, []);

  return (
    <Layout title="Predictive Patterns">
      <div
        className="glass"
        style={{
          padding: '1rem 1.5rem',
          marginBottom: '1.5rem',
          background: 'linear-gradient(135deg, rgba(6,182,212,0.1), rgba(16,185,129,0.08))',
          borderColor: 'rgba(6,182,212,0.3)',
        }}
      >
        <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
          🔬 Predictive patterns are automatically generated by the AI engine from health record data.
          They help identify and prevent disease outbreaks in rural communities.
        </p>
      </div>

      {error && <div className="alert alert-error">{error}</div>}

      {loading ? (
        <div className="spinner" />
      ) : patterns.length === 0 ? (
        <div className="empty-state glass">
          <div className="icon">🔬</div>
          <p>No predictive patterns yet. They will appear here once the AI engine processes enough health records.</p>
        </div>
      ) : (
        <div className="table-wrapper glass">
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Disease</th>
                <th>Confidence</th>
                <th>Data Points</th>
                <th>Status</th>
                <th>Last Updated</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              {patterns.map((p) => (
                <tr key={p.id}>
                  <td style={{ color: 'var(--text-muted)' }}>{p.id}</td>
                  <td style={{ fontWeight: 700, color: 'var(--cyan)' }}>{p.disease_type}</td>
                  <td style={{ minWidth: 140 }}>
                    <ConfidenceBar score={p.confidence_score} />
                  </td>
                  <td>{p.data_points_used?.toLocaleString() ?? '—'}</td>
                  <td>
                    {p.active
                      ? <span className="badge badge-low">Active</span>
                      : <span className="badge badge-default">Inactive</span>}
                  </td>
                  <td style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                    {new Date(p.last_updated).toLocaleString()}
                  </td>
                  <td style={{ maxWidth: 300, fontSize: '0.82rem', color: 'var(--text-secondary)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                    {p.pattern_description ?? '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Layout>
  );
}
